# Generated by Django 4.0.3 on 2022-05-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=14, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flights.location')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
            bases=('flights.location',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flights.location')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.country')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
            bases=('flights.location',),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flights.location')),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.region')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
            bases=('flights.location',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flights.location')),
                ('station_type', models.CharField(max_length=30, verbose_name='Тип')),
                ('settlement_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.settlement')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
            bases=('flights.location',),
        ),
    ]
