# Generated by Django 4.0.3 on 2022-05-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
    ]
