# Generated by Django 4.0.3 on 2022-05-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_location_options_alter_station_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
    ]
