# Generated by Django 4.0.3 on 2022-05-20 10:08

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0004_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 13, 8, 35, 925613), verbose_name='Дата публикации')),
                ('likes', models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='view_set', to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.note')),
                ('title', models.TextField(max_length=80, unique=True, verbose_name='Название поста')),
                ('preview_image', models.ImageField(upload_to=social.models.preview_img_upload_to, verbose_name='Превью')),
                ('location', models.ManyToManyField(blank=True, to='flights.location')),
                ('tags', models.ManyToManyField(blank=True, to='social.tag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
            bases=('social.note',),
        ),
        migrations.CreateModel(
            name='AdminArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.article')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL-заголовок')),
            ],
            options={
                'verbose_name': 'Пост администратора',
                'verbose_name_plural': 'Посты администраторов',
            },
            bases=('social.article',),
        ),
        migrations.CreateModel(
            name='CommentNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.note')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_set', to='social.note')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
            bases=('social.note',),
        ),
    ]
