# Generated by Django 4.0.3 on 2022-04-25 13:33

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2022, 4, 25, 16, 33, 12, 64711), verbose_name='Дата публикации')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.note')),
                ('title', models.TextField(max_length=30, verbose_name='Название поста')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=social.models.preview_img_upload_to, verbose_name='Превью')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публичный пост')),
                ('tags', models.ManyToManyField(blank=True, to='social.tag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
            bases=('social.note',),
        ),
        migrations.CreateModel(
            name='AdminArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.article')),
                ('slug', models.SlugField(verbose_name='URL-заголовок')),
            ],
            options={
                'verbose_name': 'Пост администратора',
                'verbose_name_plural': 'Посты администраторов',
            },
            bases=('social.article',),
        ),
        migrations.CreateModel(
            name='CommentNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.note')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_set', to='social.note')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
            bases=('social.note',),
        ),
    ]
