# Generated by Django 4.0.3 on 2022-04-26 21:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=60, verbose_name='Название поста'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 0, 22, 51, 636017), verbose_name='Дата публикации'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='views',
        ),
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.ManyToManyField(related_name='view_set', to='sessions.session'),
        ),
    ]
