# Generated by Django 4.0.3 on 2022-05-04 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_article_title_remove_note_likes_note_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 18, 57, 42, 156058), verbose_name='Дата публикации'),
        ),
    ]
