# Generated by Django 4.0.3 on 2022-05-04 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_note_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 20, 44, 45, 176654), verbose_name='Дата публикации'),
        ),
    ]
