# Generated by Django 4.0.3 on 2022-04-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=14, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.country')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.region')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('settlement_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.settlement')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
    ]
