# Generated by Django 4.0.3 on 2022-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='type',
            new_name='station_type',
        ),
    ]
