# Generated by Django 4.0.3 on 2022-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'м'), ('female', 'ж')], max_length=6, null=True),
        ),
    ]
