# Generated by Django 4.0.3 on 2022-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('женщина', 'ж'), ('мужчина', 'м')], max_length=7, null=True, verbose_name='Пол'),
        ),
    ]
