# Generated by Django 4.0.3 on 2022-05-07 13:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_paymentdata_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pasport_num',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[user.models.DocumentValidator.num_validator]),
        ),
        migrations.AlterField(
            model_name='document',
            name='pasport_series',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[user.models.DocumentValidator.num_validator]),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cc_code',
            field=models.CharField(max_length=3, validators=[user.models.DocumentValidator.num_validator], verbose_name='security code'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cc_expiry',
            field=models.DateField(max_length=5, validators=[user.models.DocumentValidator.expiry_validator], verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cc_number',
            field=models.CharField(max_length=16, validators=[user.models.DocumentValidator.num_validator], verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('женщина', 'ж'), ('мужчина', 'м')], max_length=7, null=True, verbose_name='Пол'),
        ),
    ]
