# Generated by Django 4.0.3 on 2022-05-07 13:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_document_pasport_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='cc_expiry',
            field=models.CharField(max_length=5, validators=[user.models.DocumentValidator.expiry_validator], verbose_name='expiration date'),
        ),
    ]
